name: boring-registry
automerge_delay: 1
lang: unknown
lang_version: unknown
git:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
sonarqube:
  enable: false
renovatebot:
  enable: false
launchdarkly:
  enable: false
